//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace netcreative.ca
{


    public partial class boutique
    {

        /// <summary>
        /// Propriété Master fortement typée, générée par la directive MasterType.
        /// </summary>
        public new netcreative.ca.MasterPages.Site Master
        {
            get
            {
                return ((netcreative.ca.MasterPages.Site)(base.Master));
            }
        }

    }
}
