//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace netcreative.ca
{


    public partial class AdminMaster
    {

        /// <summary>
        /// HeadTitle control.
        /// </summary>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder HeadTitle;

        /// <summary>
        /// HeadContent control.
        /// </summary>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder HeadContent;

        /// <summary>
        /// Label_CurrentUser control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label Label_CurrentUser;

        /// <summary>
        /// Link_Dashboard control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink Link_Dashboard;

        /// <summary>
        /// Link_Contact control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink Link_Contact;

        /// <summary>
        /// Link_Login control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink Link_Login;

        /// <summary>
        /// Link_Newsletter control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink Link_Newsletter;

        /// <summary>
        /// Link_Opening control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink Link_Opening;

        /// <summary>
        /// Link_Subscribers control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink Link_Subscribers;

        /// <summary>
        /// Link_Users control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink Link_Users;

        /// <summary>
        /// Link_Sql control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink Link_Sql;

        /// <summary>
        /// Button_Logout control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button Button_Logout;

        /// <summary>
        /// PageTitle control.
        /// </summary>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder PageTitle;

        /// <summary>
        /// MainContent control.
        /// </summary>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder MainContent;
    }
}
