//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace netcreative.ca
{


    public partial class ContactLog
    {

        /// <summary>
        /// Repeater control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater Repeater;

        /// <summary>
        /// TextBox_Contact_Delete control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox TextBox_Contact_Delete;

        /// <summary>
        /// Button_Contact_Delete control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button Button_Contact_Delete;
    }
}
