//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace netcreative.ca
{


    public partial class LoginLog
    {

        /// <summary>
        /// GridView_Login control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView GridView_Login;

        /// <summary>
        /// TextBox_Login_Delete control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox TextBox_Login_Delete;

        /// <summary>
        /// Button_Login_Delete control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button Button_Login_Delete;
    }
}
