//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace netcreative.ca
{


    public partial class Newsletter
    {

        /// <summary>
        /// RadioButton_Newsletter_Test control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RadioButton RadioButton_Newsletter_Test;

        /// <summary>
        /// Label_Newsletter_Email control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label Label_Newsletter_Email;

        /// <summary>
        /// TextBox_Newsletter_Email control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox TextBox_Newsletter_Email;

        /// <summary>
        /// RadioButton_Newsletter control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RadioButton RadioButton_Newsletter;

        /// <summary>
        /// TextBox_Newsletter_Object control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox TextBox_Newsletter_Object;

        /// <summary>
        /// TextBox_Newsletter_Intro control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox TextBox_Newsletter_Intro;

        /// <summary>
        /// TextBox_Newsletter_Body control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox TextBox_Newsletter_Body;

        /// <summary>
        /// TextBox_Newsletter_Greeting control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox TextBox_Newsletter_Greeting;

        /// <summary>
        /// Button_Newsletter_Send control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button Button_Newsletter_Send;
    }
}
