//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace netcreative.ca
{


    public partial class Sql
    {

        /// <summary>
        /// TextBox_Sql_Query control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox TextBox_Sql_Query;

        /// <summary>
        /// Button_Sql_Execute control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button Button_Sql_Execute;

        /// <summary>
        /// Label_Sql_Status control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label Label_Sql_Status;

        /// <summary>
        /// GridView_Sql_Result control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView GridView_Sql_Result;
    }
}
