//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace netcreative.ca
{


    public partial class Subscribers
    {

        /// <summary>
        /// GridView_Subscribe control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView GridView_Subscribe;

        /// <summary>
        /// TextBox_Subscriber_Delete control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox TextBox_Subscriber_Delete;

        /// <summary>
        /// Button_Subscriber_Delete control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button Button_Subscriber_Delete;
    }
}
