//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace netcreative.ca
{


    public partial class Users
    {

        /// <summary>
        /// DropDown_User control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList DropDown_User;

        /// <summary>
        /// TextBox_User_Name control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox TextBox_User_Name;

        /// <summary>
        /// TextBox_User_Password control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox TextBox_User_Password;

        /// <summary>
        /// TextBox_User_FirstName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox TextBox_User_FirstName;

        /// <summary>
        /// TextBox_User_LastName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox TextBox_User_LastName;

        /// <summary>
        /// Button_User_Save control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button Button_User_Save;

        /// <summary>
        /// Button_User_SaveNew control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button Button_User_SaveNew;

        /// <summary>
        /// Button_User_New control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button Button_User_New;

        /// <summary>
        /// Button_User_Delete control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button Button_User_Delete;
    }
}
